/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import static gui.SignIn.logger;
import java.awt.Color;
import java.awt.Frame;
import java.io.File;
import java.io.InputStream;
import model.MySQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JFormattedTextField;
import java.util.logging.Level;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.GRNItem;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author barth
 */
public class GRN extends javax.swing.JPanel {
    private Home home;
    HashMap<String, GRNItem> grnItemMap = new HashMap<>();

    /**
     * Creates new form GRN
     */
    public GRN(Home home) {
        initComponents();
        this.home = home;
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        grnItemTable.setDefaultRenderer(Object.class, renderer);
        generateGRNId();
        employeeEmailLabel.setText(SignIn.getEmployeeEmail());
    }
    
    private void generateGRNId() {
        long id = System.currentTimeMillis();
        grnIdField.setText(String.valueOf(id));
    }
    
    public JTextField getsupplierMobileField() {
        return supplierMobileField;
    }
    
    public JLabel getsupplierNameLabel() {
        return supplierNameLabel;
    }
    
    public JTextField getproductIdField() {
        return productIdField;
    }
    
    public JTextField getproductUPCField() {
        return productUPCField;
    }
    
    public JLabel getproductBrandLabel() {
       return productBrandLabel;
    }
    
    public JLabel getproductNameLabel() {
        return productNameLabel;
    }
    
    public JFormattedTextField getpaymentFormattedField() {
        return paymentFormattedField;
    }
    
    private void loadGRNItems() {
        DefaultTableModel model = (DefaultTableModel)grnItemTable.getModel();
        model.setRowCount(0);
        double total = 0;
        
        for (GRNItem grnItem : grnItemMap.values()) {
            Vector<String> vector = new Vector<>();
            vector.add(grnItem.getProductId());
            vector.add(grnItem.getProductUPC());
            vector.add(grnItem.getBrandName());
            vector.add(grnItem.getProductName());
            vector.add(String.valueOf(grnItem.getQty()));
            vector.add(String.valueOf(grnItem.getBuyingPrice()));
            vector.add(String.valueOf(grnItem.getSellingPrice()));
            vector.add(String.valueOf(grnItem.getMfd()));
            vector.add(String.valueOf(grnItem.getExp()));
            double itemTotal = grnItem.getQty() * grnItem.getBuyingPrice();
            total += itemTotal;
            vector.add(String.valueOf(itemTotal));
            model.addRow(vector);
        }
        
        if (typeComboBox.getSelectedItem().equals("Returned Stock")) {
            totalLabel.setText("0.00");
        }else {
            totalLabel.setText(String.valueOf(total));
        }
    }

    private void reset() {
        generateGRNId();
        supplierMobileField.setText("");
        supplierNameLabel.setText("SUPPLIER NAME");
        productIdField.setText("");
        productUPCField.setText("");
        qtyFormattedField.setText("0");
        productBrandLabel.setText("BRAND NAME");
        productNameLabel.setText("PRODUCT NAME");
        buyingPriceFormattedField.setText("0");
        sellingPriceFormattedField.setText("0");
        mfdDateChooser.setDate(null);
        expDateChooser.setDate(null);
        DefaultTableModel model = (DefaultTableModel)grnItemTable.getModel();
        model.setRowCount(0);
        totalLabel.setText("0.00");
        paymentFormattedField.setText("0");
        balanceLabel.setText("0.00");
        grnItemMap.clear();
        typeComboBox.setSelectedIndex(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        employeeEmailLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        grnIdField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        supplierMobileField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        productIdField = new javax.swing.JTextField();
        selectProductButton = new javax.swing.JButton();
        qtyFormattedField = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        productBrandLabel = new javax.swing.JLabel();
        buyingPriceFormattedField = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        mfdDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        productNameLabel = new javax.swing.JLabel();
        sellingPriceFormattedField = new javax.swing.JFormattedTextField();
        expDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        selectSupplierButton = new javax.swing.JButton();
        supplierNameLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        productUPCField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grnItemTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        totalLabel = new javax.swing.JLabel();
        paymentFormattedField = new javax.swing.JFormattedTextField();
        balanceLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        saveNPrintButton = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("GRN");

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("Employee Email :");

        employeeEmailLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        employeeEmailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeeEmailLabel.setText("EMPLOYEE EMAIL");
        employeeEmailLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("GRN ID :");

        grnIdField.setEditable(false);
        grnIdField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Supplier Mobile :");

        supplierMobileField.setEditable(false);
        supplierMobileField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Product ID :");

        productIdField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        selectProductButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        selectProductButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/select-icon.png"))); // NOI18N
        selectProductButton.setText("Select Product");
        selectProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectProductButtonActionPerformed(evt);
            }
        });

        qtyFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        qtyFormattedField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        qtyFormattedField.setText("0");
        qtyFormattedField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Quantity :");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Brand :");

        productBrandLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        productBrandLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productBrandLabel.setText("BRAND NAME");
        productBrandLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        buyingPriceFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        buyingPriceFormattedField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        buyingPriceFormattedField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("Buying Price :");

        mfdDateChooser.setDateFormatString("yyyy-MM-dd");

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setText("MFD :");

        productNameLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        productNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productNameLabel.setText("PRODUCT NAME");
        productNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        sellingPriceFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        sellingPriceFormattedField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        sellingPriceFormattedField.setText("0");
        sellingPriceFormattedField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        expDateChooser.setDateFormatString("yyyy-MM-dd");

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setText("Product :");

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel14.setText("Selling Price :");

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel15.setText("EXP :");

        selectSupplierButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        selectSupplierButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/select-icon.png"))); // NOI18N
        selectSupplierButton.setText("Select Supplier :");
        selectSupplierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectSupplierButtonActionPerformed(evt);
            }
        });

        supplierNameLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        supplierNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        supplierNameLabel.setText("SUPPLIER NAME");
        supplierNameLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        resetButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reset-icon.png"))); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add_icon.png"))); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        productUPCField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        productUPCField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productUPCFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("UPC :");

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close-icon.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(employeeEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(grnIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(supplierMobileField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(productUPCField)
                                    .addComponent(selectProductButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(productIdField))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(selectSupplierButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(supplierNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(qtyFormattedField)
                            .addComponent(mfdDateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(productBrandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buyingPriceFormattedField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(productNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(sellingPriceFormattedField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(expDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(addButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButton)))))
                .addGap(9, 9, 9))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(closeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeEmailLabel)
                    .addComponent(jLabel6)
                    .addComponent(productIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(productBrandLabel)
                    .addComponent(productNameLabel)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(grnIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectProductButton)
                    .addComponent(jLabel10)
                    .addComponent(buyingPriceFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sellingPriceFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(supplierMobileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(productUPCField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(mfdDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(expDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectSupplierButton)
                    .addComponent(supplierNameLabel)
                    .addComponent(resetButton)
                    .addComponent(addButton)
                    .addComponent(qtyFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        grnItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product UPC", "Brand", "Product", "Quantity", "Buying Price", "Selling Price", "MFD", "EXP", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grnItemTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(grnItemTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        totalLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLabel.setText("0.00");
        totalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        paymentFormattedField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        paymentFormattedField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paymentFormattedField.setText("0");
        paymentFormattedField.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        paymentFormattedField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paymentFormattedFieldKeyReleased(evt);
            }
        });

        balanceLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        balanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balanceLabel.setText("0.00");
        balanceLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));

        jLabel19.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel19.setText("Total :");

        jLabel20.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel20.setText("Payment :");

        jLabel21.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel21.setText("Balance :");

        saveNPrintButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        saveNPrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/print-icon.png"))); // NOI18N
        saveNPrintButton.setText("Save & Print");
        saveNPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveNPrintButtonActionPerformed(evt);
            }
        });

        typeComboBox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New Stock", "Returned Stock" }));
        typeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                typeComboBoxItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("Type :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveNPrintButton)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(balanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(paymentFormattedField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(jLabel19)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLabel)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveNPrintButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectSupplierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectSupplierButtonActionPerformed
        SelectSupplier selectSupplier = new SelectSupplier((Frame) SwingUtilities.getWindowAncestor(this), true, this);
        selectSupplier.setVisible(true);
    }//GEN-LAST:event_selectSupplierButtonActionPerformed

    private void selectProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectProductButtonActionPerformed
        SelectProduct selectProduct = new SelectProduct((Frame) SwingUtilities.getWindowAncestor(this), true, this);
        selectProduct.setVisible(true);
    }//GEN-LAST:event_selectProductButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String supplierMobile = supplierMobileField.getText();
        String productID = productIdField.getText();
        String productUPC = productUPCField.getText();
        String qty  = qtyFormattedField.getText();
        String buying_price = buyingPriceFormattedField.getText();
        String selling_price = sellingPriceFormattedField.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date mfd = mfdDateChooser.getDate();
        Date exp = expDateChooser.getDate();

        if (supplierMobile.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a supplier", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (productID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a product", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (productUPC.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a product", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (qty.equals("0")) {
            JOptionPane.showMessageDialog(this, "Please enter a quantity", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (qty.equals("0.00")) {
            JOptionPane.showMessageDialog(this, "Please enter a quantity", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (qty.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a quantity", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (!qty.matches("^\\d+(\\.\\d{1,2})?$")) {
            JOptionPane.showMessageDialog(this, "INVALID quantity", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (buying_price.equals("0")) {
            JOptionPane.showMessageDialog(this, "Please enter a buying price", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (buying_price.equals("0.00")) {
            JOptionPane.showMessageDialog(this, "Please enter a buying price", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (buying_price.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a buying price", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (!buying_price.matches("^(0|[1-9]\\d*)?(\\.\\d+)?(?<=\\d)$")) {
            JOptionPane.showMessageDialog(this, "INVALID buying price", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (selling_price.equals("0")) {
            JOptionPane.showMessageDialog(this, "Please enter a selling price", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (selling_price.equals("0.00")) {
            JOptionPane.showMessageDialog(this, "Please enter a selling price", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (selling_price.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a selling price", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (!selling_price.matches("^(0|[1-9]\\d*)?(\\.\\d+)?(?<=\\d)$")) {
            JOptionPane.showMessageDialog(this, "INVALID selling price", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (mfd == null) {
            JOptionPane.showMessageDialog(this, "Please enter a MFD", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (exp == null) {
            JOptionPane.showMessageDialog(this, "Please enter a EXP", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            GRNItem grnItem = new GRNItem();
            grnItem.setProductId(productIdField.getText());
            grnItem.setBrandName(productBrandLabel.getText());
            grnItem.setProductName(productNameLabel.getText());
            grnItem.setQty(Double.parseDouble(qty));
            grnItem.setBuyingPrice(Double.parseDouble(buying_price));
            grnItem.setSellingPrice(Double.parseDouble(selling_price));
            grnItem.setMfd(sdf.format(mfd));
            grnItem.setExp(sdf.format(exp));
            grnItem.setProductUPC(productUPC);

            if (grnItemMap.get(productIdField.getText()) == null) {
                grnItemMap.put(productIdField.getText(), grnItem);
                loadGRNItems();
            }else {
                GRNItem found = grnItemMap.get(productIdField.getText());

                if (found.getExp().compareTo(sdf.format(exp)) == 0
                    && found.getMfd().compareTo(sdf.format(mfd)) == 0
                    && found.getBuyingPrice() == Double.parseDouble(buying_price)
                    && found.getSellingPrice() == Double.parseDouble(selling_price)) {
                    found.setQty(found.getQty() + Double.parseDouble(qty));
                    loadGRNItems();
                }else {
                    JOptionPane.showMessageDialog(this, "This GRN item already exists with different dates and prices",
                        "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
        productIdField.setText("");
        productUPCField.setText("");
        qtyFormattedField.setText("0");
        productBrandLabel.setText("BRAND NAME");
        productNameLabel.setText("PRODUCT NAME");
        buyingPriceFormattedField.setText("0");
        sellingPriceFormattedField.setText("0");
        mfdDateChooser.setDate(null);
        expDateChooser.setDate(null);
    }//GEN-LAST:event_addButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        reset();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void paymentFormattedFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentFormattedFieldKeyReleased
        String total = totalLabel.getText();
        String payment = paymentFormattedField.getText();
        
        if (payment.isEmpty()) {
            payment = "0";
        }else if (!payment.matches("^(0|[1-9]\\d*)?(\\.\\d+)?(?<=\\d)$")) {
            balanceLabel.setText("INVALID");
            balanceLabel.setForeground(Color.red);
        }else {
            double balance = Double.parseDouble(payment) - Double.parseDouble(total);
            balanceLabel.setText(String.valueOf(balance));
            balanceLabel.setForeground(Color.white);
        }
    }//GEN-LAST:event_paymentFormattedFieldKeyReleased

    private void saveNPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveNPrintButtonActionPerformed
        try {
            ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `grn` WHERE `id` = '"+grnIdField.getText()+"'");
            
            if (resultSet.next()) {
                JOptionPane.showMessageDialog(this, "This grn already exists", "Warning", JOptionPane.WARNING_MESSAGE);
            }else {
                String grnId = grnIdField.getText();
                String supplierMobile = supplierMobileField.getText();
                String employeeEmail = employeeEmailLabel.getText();
                String dateTime = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());
                String paidAmount = paymentFormattedField.getText();
                //SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                int rowCount = grnItemTable.getRowCount();

                if (rowCount == 0) {
                    JOptionPane.showMessageDialog(this, "Please add GRN item(s) to GRN", "Warning", JOptionPane.WARNING_MESSAGE);
                }else if (typeComboBox.getSelectedItem().equals("New Stock")) {
                    MySQL.executeIUD("INSERT INTO `grn` VALUES('"+grnId+"', '"+supplierMobile+"', '"+dateTime+"', "
                        + "'"+employeeEmail+"', '"+paidAmount+"')");

                    for (GRNItem grnItem : grnItemMap.values()) {
                        ResultSet resultSet1 = MySQL.executeSearch("SELECT * FROM `stock` WHERE "
                                + "`product_id` = '"+grnItem.getProductId()+"' AND "
                                + "`price` = '"+grnItem.getSellingPrice()+"' AND "
                                + "`mfd` = '"+grnItem.getMfd()+"' AND "
                                + "`exp` = '"+grnItem.getExp()+"'");
                        String stockID = "";

                        if (resultSet1.next()) {
                            stockID = resultSet1.getString("id");
                            String currentQty = resultSet1.getString("qty");
                            String updatedQty = String.valueOf(Double.parseDouble(currentQty) + grnItem.getQty());
                            MySQL.executeIUD("UPDATE `stock` SET `qty` = '"+updatedQty+"' WHERE `id` = '"+stockID+"'");
                        }else {
                            MySQL.executeIUD("INSERT INTO `stock`(`price`, `qty`, `mfd`, `exp`, `barcode`, `product_id`) "
                                    + "VALUES('"+grnItem.getSellingPrice()+"', '"+grnItem.getQty()+"', "
                                    + "'"+grnItem.getMfd()+"', '"+grnItem.getExp()+"', 'Pending', "
                                    + "'"+grnItem.getProductId()+"')");

                            ResultSet resultSet2 = MySQL.executeSearch("SELECT * FROM `stock` WHERE "
                                    + "`product_id` = '"+grnItem.getProductId()+"' AND "
                                    + "`price` = '"+grnItem.getSellingPrice()+"' AND "
                                    + "`mfd` = '"+grnItem.getMfd()+"' AND "
                                    + "`exp` = '"+grnItem.getExp()+"'");

                            if (resultSet2.next()) {
                                stockID = resultSet2.getString("id");
                            }
                        }

                        MySQL.executeIUD("INSERT INTO `grn_item`(`grn_id`, `qty`, `price`, `stock_id`) "
                                + "VALUES('"+grnId+"', '"+grnItem.getQty()+"', '"+grnItem.getBuyingPrice()+"', '"+stockID+"')");
                    }
                    
                    InputStream path = this.getClass().getResourceAsStream("/reports/gh_grn.jasper");
                    HashMap<String, Object> parameters = new HashMap<>();
                    parameters.put("Parameter1", employeeEmailLabel.getText());
                    parameters.put("Parameter2", grnIdField.getText());
                    parameters.put("Parameter3", supplierMobileField.getText());
                    parameters.put("Parameter4", dateTime);
                    parameters.put("Parameter5", totalLabel.getText());
                    parameters.put("Parameter6", paymentFormattedField.getText());
                    parameters.put("Parameter7", balanceLabel.getText());
                    parameters.put("Parameter8", String.valueOf(typeComboBox.getSelectedItem()));
                    
                    String appDir = new File("").getAbsolutePath(); // Get the application's directory
                    String reportsFolder = appDir + File.separator + "ExportedReports"; // Main folder path
                    // Create the main "ExportedReports" folder if it doesn't exist
                    File mainDirectory = new File(reportsFolder);
                    if (!mainDirectory.exists()) {
                        mainDirectory.mkdirs();
                    }
                    // Create subfolder for "Grn Reports" if it doesn't exist
                    String grnReportsFolder = reportsFolder + File.separator + "Grn Reports";
                    File grnDirectory = new File(grnReportsFolder);
                    if (!grnDirectory.exists()) {
                        grnDirectory.mkdirs();
                    }
                    // Path to export the PDF file (inside "Grn Reports" subfolder)
                    String outputPath = grnReportsFolder + File.separator + "Grn_report_" + grnId + ".pdf";
                    
                    JRTableModelDataSource dataSource = new JRTableModelDataSource(grnItemTable.getModel());
                    JasperPrint report = JasperFillManager.fillReport(path, parameters, dataSource);
                    JasperViewer.viewReport(report, false);
                    JasperPrintManager.printReport(report, false);
                    JasperExportManager.exportReportToPdfFile(report, outputPath);
                    reset();
                    logger.log(Level.INFO, "Successfully generated GRN " + grnId + " for new stock");
                }else if (typeComboBox.getSelectedItem().equals("Returned Stock")) {
                    MySQL.executeIUD("INSERT INTO `grn` VALUES('"+grnId+"', '"+supplierMobile+"', '"+dateTime+"', "
                        + "'"+employeeEmail+"', '"+paidAmount+"')");

                    for (GRNItem grnItem : grnItemMap.values()) {
                        String stockID = "";
                        
                        MySQL.executeIUD("INSERT INTO `stock`(`price`, `qty`, `mfd`, `exp`, `barcode`, `product_id`) "
                                    + "VALUES('"+grnItem.getSellingPrice()+"', '"+grnItem.getQty()+"', "
                                    + "'"+grnItem.getMfd()+"', '"+grnItem.getExp()+"', 'Pending', "
                                    + "'"+grnItem.getProductId()+"')");

                        ResultSet resultSet1 = MySQL.executeSearch("SELECT * FROM `stock` WHERE "
                                + "`product_id` = '"+grnItem.getProductId()+"' AND "
                                + "`price` = '"+grnItem.getSellingPrice()+"' AND "
                                + "`mfd` = '"+grnItem.getMfd()+"' AND "
                                + "`exp` = '"+grnItem.getExp()+"'");

                        if (resultSet1.next()) {
                            stockID = resultSet1.getString("id");
                        }

                        MySQL.executeIUD("INSERT INTO `grn_item`(`grn_id`, `qty`, `price`, `stock_id`) "
                                + "VALUES('"+grnId+"', '"+grnItem.getQty()+"', '"+grnItem.getBuyingPrice()+"', '"+stockID+"')");
                        
                        ResultSet resultSet2 = MySQL.executeSearch("SELECT * FROM `returning_stock` "
                                    + "INNER JOIN `stock` ON `returning_stock`.`stock_id` = `stock`.`id` "
                                    + "INNER JOIN `grn_item` ON `stock`.`id` = `grn_item`.`stock_id` "
                                    + "INNER JOIN `grn` ON `grn_item`.`grn_id` = `grn`.`id` "
                                    + "INNER JOIN `supplier` ON `grn`.`supplier_mobile` = `supplier`.`mobile` "
                                    + "INNER JOIN `product` ON `stock`.`product_id` = `product`.`id` "
                                    + "INNER JOIN `return_invoice_item` "
                                    + "ON `return_invoice_item`.`returning_stock_id` = `returning_stock`.`id` "
                                    + "INNER JOIN `return_invoice` "
                                    + "ON `return_invoice_item`.`return_invoice_id` = `return_invoice`.`id` "
                                    + "WHERE `returning_stock`.`qty` = '"+grnItem.getQty()+"' "
                                    + "AND `grn_item`.`price` = '"+grnItem.getBuyingPrice()+"' "
                                    + "AND `supplier`.`mobile` = '"+supplierMobile+"' "
                                    + "AND `product`.`id` = '"+grnItem.getProductId()+"'");
                        
                        if (resultSet2.next()) {
                            MySQL.executeIUD("UPDATE `returning_stock` SET `returning_stock_status_id` = 2 "
                                    + "WHERE `returning_stock`.`id` = '"+resultSet2.getString("returning_stock.id")+"'");

                            MySQL.executeIUD("UPDATE `return_invoice` SET `return_invoice_status_id` = 2 "
                                    + "WHERE `return_invoice`.`id` = '"+resultSet2.getString("return_invoice.id")+"'");
                        }
                    }
                    
                    InputStream path = this.getClass().getResourceAsStream("/reports/gh_grn.jasper");
                    HashMap<String, Object> parameters = new HashMap<>();
                    parameters.put("Parameter1", employeeEmailLabel.getText());
                    parameters.put("Parameter2", grnIdField.getText());
                    parameters.put("Parameter3", supplierMobileField.getText());
                    parameters.put("Parameter4", dateTime);
                    parameters.put("Parameter5", totalLabel.getText());
                    parameters.put("Parameter6", paymentFormattedField.getText());
                    parameters.put("Parameter7", balanceLabel.getText());
                    parameters.put("Parameter8", String.valueOf(typeComboBox.getSelectedItem()));
                    
                    String appDir = new File("").getAbsolutePath(); // Get the application's directory
                    String reportsFolder = appDir + File.separator + "ExportedReports"; // Main folder path
                    // Create the main "ExportedReports" folder if it doesn't exist
                    File mainDirectory = new File(reportsFolder);
                    if (!mainDirectory.exists()) {
                        mainDirectory.mkdirs();
                    }
                    // Create subfolder for "Grn Reports" if it doesn't exist
                    String grnReportsFolder = reportsFolder + File.separator + "Grn Reports";
                    File grnDirectory = new File(grnReportsFolder);
                    if (!grnDirectory.exists()) {
                        grnDirectory.mkdirs();
                    }
                    // Path to export the PDF file (inside "Grn Reports" subfolder)
                    String outputPath = grnReportsFolder + File.separator + "Grn_report_" + grnId + ".pdf";
                    
                    JRTableModelDataSource dataSource = new JRTableModelDataSource(grnItemTable.getModel());
                    JasperPrint report = JasperFillManager.fillReport(path, parameters, dataSource);
                    JasperViewer.viewReport(report, false);
                    JasperPrintManager.printReport(report, false);
                    JasperExportManager.exportReportToPdfFile(report, outputPath);
                    reset();
                    logger.log(Level.INFO, "Successfully generated GRN " + grnId + " for returned stock");
                }
            }
        } catch (Exception e) {
            //e.printStackTrace();
            logger.log(Level.WARNING, "Exception", e);
        }
    }//GEN-LAST:event_saveNPrintButtonActionPerformed

    private void productUPCFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productUPCFieldActionPerformed
        String upc = productUPCField.getText();
        
        try {
            if (upc.length() == 13) {
                ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `product` "
                        + "INNER JOIN `brand` ON `product`.`brand_id` = `brand`.`id` "
                        + "WHERE `product`.`upc` = '"+upc+"'");
                
                if (resultSet.next()) {
                    productIdField.setText(resultSet.getString("product.id"));
                    productBrandLabel.setText(resultSet.getString("brand.name"));
                    productNameLabel.setText(resultSet.getString("product.name"));
                }else {
                    JOptionPane.showMessageDialog(this, "No product found", "Warning", JOptionPane.WARNING_MESSAGE);
                }
            }else {
                JOptionPane.showMessageDialog(this, "Invalid UPC", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            //e.printStackTrace();
            logger.log(Level.WARNING, "Exception", e);
        }
    }//GEN-LAST:event_productUPCFieldActionPerformed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        this.home.removeGRN();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void typeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeComboBoxItemStateChanged
        if (typeComboBox.getSelectedItem().equals("New Stock")) {
                getpaymentFormattedField().setEnabled(true);
        }else if (typeComboBox.getSelectedItem().equals("Returned Stock")) {
            getpaymentFormattedField().setEnabled(false);
        }
    }//GEN-LAST:event_typeComboBoxItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JFormattedTextField buyingPriceFormattedField;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JLabel employeeEmailLabel;
    private com.toedter.calendar.JDateChooser expDateChooser;
    private javax.swing.JTextField grnIdField;
    private javax.swing.JTable grnItemTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser mfdDateChooser;
    private javax.swing.JFormattedTextField paymentFormattedField;
    private javax.swing.JLabel productBrandLabel;
    private javax.swing.JTextField productIdField;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JTextField productUPCField;
    private javax.swing.JFormattedTextField qtyFormattedField;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveNPrintButton;
    private javax.swing.JButton selectProductButton;
    private javax.swing.JButton selectSupplierButton;
    private javax.swing.JFormattedTextField sellingPriceFormattedField;
    private javax.swing.JTextField supplierMobileField;
    private javax.swing.JLabel supplierNameLabel;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JComboBox<String> typeComboBox;
    // End of variables declaration//GEN-END:variables
}
