/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import static gui.SignIn.logger;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import model.MySQL;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;
import java.util.logging.Level;

/**
 *
 * @author barth
 */
public class Reports extends javax.swing.JPanel {
    private Home home;

    /**
     * Creates new form Reports
     */
    public Reports(Home home) {
        initComponents();
        this.home = home;
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        reportsTable.setDefaultRenderer(Object.class, renderer);
        loadReports();
    }
    
    private void loadReports() {
        try {
            String selectedReportType = String.valueOf(reportTypeComboBox.getSelectedItem());
            String reportType = "";
            
            if (selectedReportType.equals("GRNs")) {
                reportType = "grn";
            }else if (selectedReportType.equals("Invoices")) {
                reportType = "invoice";
            }else if (selectedReportType.equals("Return Receipts")) {
                reportType = "customer_return_receipt";
            }else if (selectedReportType.equals("Return Invoices")) {
                reportType = "return_invoice";
            }else if (selectedReportType.equals("Return Receipts")) {
                reportType = "customer_return_receipt";
            }else if (selectedReportType.equals("Return Invoices")) {
                reportType = "return_invoice";
            }
            
            String query = "SELECT `id`, `date`, `employee`.`email` FROM `"+reportType+"` INNER JOIN `employee` "
                    + "ON `"+reportType+"`.`employee_email` = `employee`.`email`";
            Date dateFrom = null;
            Date dateTo = null;
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            
            if (dateFromDateChooser.getDate() != null) {
                dateFrom = dateFromDateChooser.getDate();
                query += " WHERE `"+reportType+"`.`date` > '"+format.format(dateFrom)+"' AND ";
            }
            
            if (dateToDateChooser.getDate() != null) {
                dateTo = dateToDateChooser.getDate();
                query += "`"+reportType+"`.`date` < '"+format.format(dateTo)+"'";
            }
            
            String sort = String.valueOf(sortByComboBox.getSelectedItem());
            query += " ORDER BY ";
            
            if (sort.equals("Date ASC")) {
                query += "`"+reportType+"`.`date` ASC";
            }else if (sort.equals("Date DESC")) {
                query += "`"+reportType+"`.`date` DESC";
            }else if (sort.equals("Employee ASC")) {
                query = query.replace(" ORDER BY ", " GROUP BY `id`, `date`, `employee`.`email` "
                        + "ORDER BY `employee`.`email` ASC, `date` DESC");
            }else if (sort.equals("Employee DESC")) {
                query = query.replace(" ORDER BY ", " GROUP BY `id`, `date`, `employee`.`email` "
                        + "ORDER BY `employee`.`email` DESC, `date` DESC");
            }
            
            ResultSet resultSet = MySQL.executeSearch(query);
            DefaultTableModel model = (DefaultTableModel)reportsTable.getModel();
            model.setRowCount(0);
            
            while(resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("id"));
                vector.add(resultSet.getString("date"));
                vector.add(resultSet.getString("employee.email"));
                model.addRow(vector);
            }
        } catch (Exception e) {
            //e.printStackTrace();
            logger.log(Level.WARNING, "Exception", e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        reportsTable = new javax.swing.JTable();
        dateFromDateChooser = new com.toedter.calendar.JDateChooser();
        sortByComboBox = new javax.swing.JComboBox<>();
        dateToDateChooser = new com.toedter.calendar.JDateChooser();
        resetButton = new javax.swing.JButton();
        findButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        closeLabel = new javax.swing.JLabel();
        reportTypeComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        otherViewButton = new javax.swing.JButton();
        otherPrintButton = new javax.swing.JButton();
        otherExportButton = new javax.swing.JButton();
        employeesRadioButton = new javax.swing.JRadioButton();
        customersRadioButton = new javax.swing.JRadioButton();
        suppliersRadioButton = new javax.swing.JRadioButton();
        productsRadioButton = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        salesTypeComboBox = new javax.swing.JComboBox<>();
        salesViewButton = new javax.swing.JButton();
        salesPrintButton = new javax.swing.JButton();
        salesExportButton = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 153, 255));
        jLabel2.setText("Reports");

        reportsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Date", "Employee Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        reportsTable.getTableHeader().setReorderingAllowed(false);
        reportsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reportsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(reportsTable);

        dateFromDateChooser.setDateFormatString("yyyy-MM-dd");

        sortByComboBox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        sortByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date DESC", "Date ASC", "Employee ASC", "Employee DESC" }));
        sortByComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortByComboBoxItemStateChanged(evt);
            }
        });

        dateToDateChooser.setDateFormatString("yyyy-MM-dd");

        resetButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        resetButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/reset-icon.png"))); // NOI18N
        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        findButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        findButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/search-icon.png"))); // NOI18N
        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel9.setText("To");

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("From");

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setText("Sort By :");

        closeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/close-icon.png"))); // NOI18N
        closeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLabelMouseClicked(evt);
            }
        });

        reportTypeComboBox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        reportTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GRNs", "Invoices", "Return Receipts", "Return Invoices", " " }));
        reportTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                reportTypeComboBoxItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Type :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeLabel))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateFromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(reportTypeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateToDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(findButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetButton, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(closeLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(dateFromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(dateToDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reportTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(findButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel3.setText("Other Reports");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Select Type :");

        otherViewButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        otherViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view-icon.png"))); // NOI18N
        otherViewButton.setText("View");
        otherViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherViewButtonActionPerformed(evt);
            }
        });

        otherPrintButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        otherPrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/print-icon.png"))); // NOI18N
        otherPrintButton.setText("Print");
        otherPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherPrintButtonActionPerformed(evt);
            }
        });

        otherExportButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        otherExportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/export-icon.png"))); // NOI18N
        otherExportButton.setText("Export");
        otherExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherExportButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(employeesRadioButton);
        employeesRadioButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        employeesRadioButton.setText("Employees");
        employeesRadioButton.setActionCommand("Employees");

        buttonGroup1.add(customersRadioButton);
        customersRadioButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        customersRadioButton.setText("Customers");
        customersRadioButton.setActionCommand("Customers");

        buttonGroup1.add(suppliersRadioButton);
        suppliersRadioButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        suppliersRadioButton.setText("Suppliers");
        suppliersRadioButton.setActionCommand("Suppliers");

        buttonGroup1.add(productsRadioButton);
        productsRadioButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        productsRadioButton.setText("Products");
        productsRadioButton.setActionCommand("Products");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(otherViewButton)
                                .addGap(6, 6, 6)
                                .addComponent(otherPrintButton)
                                .addGap(6, 6, 6)
                                .addComponent(otherExportButton))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(employeesRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(customersRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(suppliersRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(productsRadioButton)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(employeesRadioButton)
                    .addComponent(customersRadioButton)
                    .addComponent(suppliersRadioButton)
                    .addComponent(productsRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherViewButton)
                    .addComponent(otherPrintButton)
                    .addComponent(otherExportButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("Sales Reports");

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("Select Type :");

        salesTypeComboBox.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        salesTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Daily", "Weekly", "Monthly" }));

        salesViewButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        salesViewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/view-icon.png"))); // NOI18N
        salesViewButton.setText("View");
        salesViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesViewButtonActionPerformed(evt);
            }
        });

        salesPrintButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        salesPrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/print-icon.png"))); // NOI18N
        salesPrintButton.setText("Print");
        salesPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesPrintButtonActionPerformed(evt);
            }
        });

        salesExportButton.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        salesExportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/export-icon.png"))); // NOI18N
        salesExportButton.setText("Export");
        salesExportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesExportButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(salesViewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salesTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(salesPrintButton)
                        .addGap(6, 6, 6)
                        .addComponent(salesExportButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salesTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salesViewButton)
                    .addComponent(salesPrintButton)
                    .addComponent(salesExportButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sortByComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortByComboBoxItemStateChanged
        loadReports();
    }//GEN-LAST:event_sortByComboBoxItemStateChanged

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        if (dateFromDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Select a date to find from", "Warning", JOptionPane.WARNING_MESSAGE);
        }else if (dateToDateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Select a date to find till", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            loadReports();
        }
    }//GEN-LAST:event_findButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        sortByComboBox.setSelectedIndex(0);
        dateFromDateChooser.setDate(null);
        dateToDateChooser.setDate(null);
        reportTypeComboBox.setSelectedIndex(0);
        reportsTable.clearSelection();
        loadReports();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void reportsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsTableMouseClicked
        int row = reportsTable.getSelectedRow();
        String reportID = String.valueOf(reportsTable.getValueAt(row, 0));
        String selectedReportType = String.valueOf(reportTypeComboBox.getSelectedItem());
        String reportsTypeFolder = "";
        String pdfFilePath = "";
        
        if (evt.getClickCount() == 2) {
            try {
                // Get the application's directory
                String appDir = new File("").getAbsolutePath();
                // Path to the "Invoice Reports" subfolder inside "ExportedReports"
                if (selectedReportType.equals("GRNs")) {
                    reportsTypeFolder = appDir + File.separator + "ExportedReports" + File.separator + "Grn Reports";
                }else if (selectedReportType.equals("Invoices")) {
                    reportsTypeFolder = appDir + File.separator + "ExportedReports" + File.separator + "Invoice Reports";
                }else if (selectedReportType.equals("Return Receipts")) {
                    reportsTypeFolder = appDir + File.separator + "ExportedReports" + File.separator + "Return Receipt Reports";
                }else if (selectedReportType.equals("Return Invoices")) {
                    reportsTypeFolder = appDir + File.separator + "ExportedReports" + File.separator + "Return Invoice Reports";
                }
                // Build the full file path of the invoice report PDF
                if (selectedReportType.equals("GRNs")) {
                    pdfFilePath = reportsTypeFolder + File.separator + "Grn_report_" + reportID + ".pdf";
                }else if (selectedReportType.equals("Invoices")) {
                    pdfFilePath = reportsTypeFolder + File.separator + "Invoice_report_" + reportID + ".pdf";
                }else if (selectedReportType.equals("Return Receipts")) {
                    pdfFilePath = reportsTypeFolder + File.separator + "Return_receipt_report_" + reportID + ".pdf";
                }else if (selectedReportType.equals("Return Invoices")) {
                    pdfFilePath = reportsTypeFolder + File.separator + "Return_invoice_report_" + reportID + ".pdf";
                }
                // Create a File object for the PDF
                File pdfFile = new File(pdfFilePath);
                // Check if the file exists
                if (pdfFile.exists()) {
                    // Check if the desktop is supported
                    if (Desktop.isDesktopSupported()) {
                        Desktop desktop = Desktop.getDesktop();
                        try {
                            // Open the PDF file with the default system viewer
                            desktop.open(pdfFile);
                            logger.log(Level.INFO, "Viewed PDF report: " + pdfFilePath);
                        } catch (IOException e) {
                            //e.printStackTrace();
                            logger.log(Level.WARNING, "Exception", e);
                            JOptionPane.showMessageDialog(null, "Error opening the PDF file: " + e.getMessage());
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Desktop feature not supported, cannot open PDF.");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "PDF file does not exist: " + pdfFilePath);
                }
            } catch (Exception e) {
                //e.printStackTrace();
                logger.log(Level.WARNING, "Exception", e);
                JOptionPane.showMessageDialog(null, "Error viewing report: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_reportsTableMouseClicked

    private void salesViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesViewButtonActionPerformed
        try {
            String sort = String.valueOf(salesTypeComboBox.getSelectedItem());
            String date = "";
            ResultSet resultSet = null;
            InputStream filePath = null;
        
            if (sort.equals("Daily")) {
                date = new SimpleDateFormat("yyyy-MMMM-dd").format(new Date());
                resultSet = MySQL.executeSearch("SELECT COUNT(i.id) AS invoice_count, "
                        + "SUM(i.paid_amount - IFNULL(crr.return_total, 0)) AS net_paid_amount, "
                        + "SUM(IFNULL(ii.total_qty, 0) - IFNULL(cri.return_qty, 0)) AS net_qty, "
                        + "SUM(i.discount) AS total_discount FROM invoice i "
                        + "LEFT JOIN (SELECT invoice_id, SUM(qty) AS total_qty FROM invoice_item "
                        + "GROUP BY invoice_id) ii ON i.id = ii.invoice_id LEFT JOIN (SELECT invoice_id, "
                        + "SUM(return_total) AS return_total FROM customer_return_receipt "
                        + "GROUP BY invoice_id) crr ON i.id = crr.invoice_id "
                        + "LEFT JOIN (SELECT crr.invoice_id, SUM(cri.qty) AS return_qty FROM customer_return_item cri "
                        + "INNER JOIN customer_return_receipt crr ON cri.customer_return_receipt_id = crr.id "
                        + "GROUP BY crr.invoice_id) cri ON i.id = cri.invoice_id WHERE DATE(i.date) = CURDATE()");
                filePath = this.getClass().getResourceAsStream("/reports/gh_sales_daily.jasper");
            }else if (sort.equals("Weekly")) {
                date = new SimpleDateFormat("yyyy-MMMM-W").format(new Date());
                resultSet = MySQL.executeSearch("SELECT COUNT(i.id) AS invoice_count, "
                        + "SUM(i.paid_amount - IFNULL(crr.return_total, 0)) AS net_paid_amount, "
                        + "SUM(IFNULL(ii.total_qty, 0) - IFNULL(cri.return_qty, 0)) AS net_qty, "
                        + "SUM(i.discount) AS total_discount FROM invoice i "
                        + "LEFT JOIN (SELECT invoice_id, SUM(qty) AS total_qty FROM invoice_item "
                        + "GROUP BY invoice_id) ii ON i.id = ii.invoice_id LEFT JOIN (SELECT invoice_id, "
                        + "SUM(return_total) AS return_total FROM customer_return_receipt "
                        + "GROUP BY invoice_id) crr ON i.id = crr.invoice_id "
                        + "LEFT JOIN (SELECT crr.invoice_id, SUM(cri.qty) AS return_qty FROM customer_return_item cri "
                        + "INNER JOIN customer_return_receipt crr ON cri.customer_return_receipt_id = crr.id "
                        + "GROUP BY crr.invoice_id) cri ON i.id = cri.invoice_id WHERE WEEK(DATE(i.date)) = WEEK(CURDATE())");
                filePath = this.getClass().getResourceAsStream("/reports/gh_sales_weekly.jasper");
            }else if (sort.equals("Monthly")) {
                date = new SimpleDateFormat("yyyy-MMMM").format(new Date());
                resultSet = MySQL.executeSearch("SELECT COUNT(i.id) AS invoice_count, "
                        + "SUM(i.paid_amount - IFNULL(crr.return_total, 0)) AS net_paid_amount, "
                        + "SUM(IFNULL(ii.total_qty, 0) - IFNULL(cri.return_qty, 0)) AS net_qty, "
                        + "SUM(i.discount) AS total_discount FROM invoice i "
                        + "LEFT JOIN (SELECT invoice_id, SUM(qty) AS total_qty FROM invoice_item "
                        + "GROUP BY invoice_id) ii ON i.id = ii.invoice_id LEFT JOIN (SELECT invoice_id, "
                        + "SUM(return_total) AS return_total FROM customer_return_receipt "
                        + "GROUP BY invoice_id) crr ON i.id = crr.invoice_id "
                        + "LEFT JOIN (SELECT crr.invoice_id, SUM(cri.qty) AS return_qty FROM customer_return_item cri "
                        + "INNER JOIN customer_return_receipt crr ON cri.customer_return_receipt_id = crr.id "
                        + "GROUP BY crr.invoice_id) cri ON i.id = cri.invoice_id WHERE MONTH(DATE(i.date)) = MONTH(CURDATE())");
                filePath = this.getClass().getResourceAsStream("/reports/gh_sales_monthly.jasper");
            }
            
            if (resultSet.next()) {
                String totalSales = resultSet.getString("invoice_count");
                String totalRevenue = resultSet.getString("net_paid_amount");
                String totalUnitsSold = resultSet.getString("net_qty");
                String totalDiscounts = resultSet.getString("total_discount");

                InputStream path = filePath;
                HashMap<String, Object> parameters = new HashMap<>();
                parameters.put("Parameter1", date);
                parameters.put("Parameter2", totalSales);
                parameters.put("Parameter3", totalRevenue);
                parameters.put("Parameter4", totalUnitsSold);
                parameters.put("Parameter5", totalDiscounts);

                JasperPrint report = JasperFillManager.fillReport(path, parameters, MySQL.connection);
                JasperViewer.viewReport(report, false);
                logger.log(Level.INFO, "Viewed " + sort + " sales report for " + date);
            }else {
                logger.log(Level.INFO, "Error viewing " + sort + " sales report for " + date);
                JOptionPane.showMessageDialog(this, "Error viewing report", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            //e.printStackTrace();
            logger.log(Level.WARNING, "Exception", e);
        }
    }//GEN-LAST:event_salesViewButtonActionPerformed

    private void salesPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesPrintButtonActionPerformed
        try {
            String sort = String.valueOf(salesTypeComboBox.getSelectedItem());
            String date = "";
            ResultSet resultSet = null;
            InputStream filePath = null;
        
            if (sort.equals("Daily")) {
                date = new SimpleDateFormat("yyyy-MMMM-dd").format(new Date());
                resultSet = MySQL.executeSearch("SELECT COUNT(i.id) AS invoice_count, "
                        + "SUM(i.paid_amount - IFNULL(crr.return_total, 0)) AS net_paid_amount, "
                        + "SUM(IFNULL(ii.total_qty, 0) - IFNULL(cri.return_qty, 0)) AS net_qty, "
                        + "SUM(i.discount) AS total_discount FROM invoice i "
                        + "LEFT JOIN (SELECT invoice_id, SUM(qty) AS total_qty FROM invoice_item "
                        + "GROUP BY invoice_id) ii ON i.id = ii.invoice_id LEFT JOIN (SELECT invoice_id, "
                        + "SUM(return_total) AS return_total FROM customer_return_receipt "
                        + "GROUP BY invoice_id) crr ON i.id = crr.invoice_id "
                        + "LEFT JOIN (SELECT crr.invoice_id, SUM(cri.qty) AS return_qty FROM customer_return_item cri "
                        + "INNER JOIN customer_return_receipt crr ON cri.customer_return_receipt_id = crr.id "
                        + "GROUP BY crr.invoice_id) cri ON i.id = cri.invoice_id WHERE DATE(i.date) = CURDATE()");
                filePath = this.getClass().getResourceAsStream("/reports/gh_sales_daily.jasper");
            }else if (sort.equals("Weekly")) {
                date = new SimpleDateFormat("yyyy-MMMM-W").format(new Date());
                resultSet = MySQL.executeSearch("SELECT COUNT(i.id) AS invoice_count, "
                        + "SUM(i.paid_amount - IFNULL(crr.return_total, 0)) AS net_paid_amount, "
                        + "SUM(IFNULL(ii.total_qty, 0) - IFNULL(cri.return_qty, 0)) AS net_qty, "
                        + "SUM(i.discount) AS total_discount FROM invoice i "
                        + "LEFT JOIN (SELECT invoice_id, SUM(qty) AS total_qty FROM invoice_item "
                        + "GROUP BY invoice_id) ii ON i.id = ii.invoice_id LEFT JOIN (SELECT invoice_id, "
                        + "SUM(return_total) AS return_total FROM customer_return_receipt "
                        + "GROUP BY invoice_id) crr ON i.id = crr.invoice_id "
                        + "LEFT JOIN (SELECT crr.invoice_id, SUM(cri.qty) AS return_qty FROM customer_return_item cri "
                        + "INNER JOIN customer_return_receipt crr ON cri.customer_return_receipt_id = crr.id "
                        + "GROUP BY crr.invoice_id) cri ON i.id = cri.invoice_id WHERE WEEK(DATE(i.date)) = WEEK(CURDATE())");
                filePath = this.getClass().getResourceAsStream("/reports/gh_sales_weekly.jasper");
            }else if (sort.equals("Monthly")) {
                date = new SimpleDateFormat("yyyy-MMMM").format(new Date());
                resultSet = MySQL.executeSearch("SELECT COUNT(i.id) AS invoice_count, "
                        + "SUM(i.paid_amount - IFNULL(crr.return_total, 0)) AS net_paid_amount, "
                        + "SUM(IFNULL(ii.total_qty, 0) - IFNULL(cri.return_qty, 0)) AS net_qty, "
                        + "SUM(i.discount) AS total_discount FROM invoice i "
                        + "LEFT JOIN (SELECT invoice_id, SUM(qty) AS total_qty FROM invoice_item "
                        + "GROUP BY invoice_id) ii ON i.id = ii.invoice_id LEFT JOIN (SELECT invoice_id, "
                        + "SUM(return_total) AS return_total FROM customer_return_receipt "
                        + "GROUP BY invoice_id) crr ON i.id = crr.invoice_id "
                        + "LEFT JOIN (SELECT crr.invoice_id, SUM(cri.qty) AS return_qty FROM customer_return_item cri "
                        + "INNER JOIN customer_return_receipt crr ON cri.customer_return_receipt_id = crr.id "
                        + "GROUP BY crr.invoice_id) cri ON i.id = cri.invoice_id WHERE MONTH(DATE(i.date)) = MONTH(CURDATE())");
                filePath = this.getClass().getResourceAsStream("/reports/gh_sales_monthly.jasper");
            }
            
            if (resultSet.next()) {
                String totalSales = resultSet.getString("invoice_count");
                String totalRevenue = resultSet.getString("net_paid_amount");
                String totalUnitsSold = resultSet.getString("net_qty");
                String totalDiscounts = resultSet.getString("total_discount");

                InputStream path = filePath;
                HashMap<String, Object> parameters = new HashMap<>();
                parameters.put("Parameter1", date);
                parameters.put("Parameter2", totalSales);
                parameters.put("Parameter3", totalRevenue);
                parameters.put("Parameter4", totalUnitsSold);
                parameters.put("Parameter5", totalDiscounts);

                JasperPrint report = JasperFillManager.fillReport(path, parameters, MySQL.connection);
                JasperPrintManager.printReport(report, false);
                logger.log(Level.INFO, "Printed " + sort + " sales report for " + date);
            }else {
                logger.log(Level.INFO, "Error printing " + sort + " sales report for " + date);
                JOptionPane.showMessageDialog(this, "Error printing report", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            //e.printStackTrace();
            logger.log(Level.WARNING, "Exception", e);
        }
    }//GEN-LAST:event_salesPrintButtonActionPerformed

    private void salesExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesExportButtonActionPerformed
        try {
            String sort = String.valueOf(salesTypeComboBox.getSelectedItem());
            String date = "";
            ResultSet resultSet = null;
            InputStream filePath = null;
            String salesReportsTypeFolder = "";
            String reportFilePath = "";
        
            if (sort.equals("Daily")) {
                date = new SimpleDateFormat("yyyy-MMMM-dd").format(new Date());
                resultSet = MySQL.executeSearch("SELECT COUNT(i.id) AS invoice_count, "
                        + "SUM(i.paid_amount - IFNULL(crr.return_total, 0)) AS net_paid_amount, "
                        + "SUM(IFNULL(ii.total_qty, 0) - IFNULL(cri.return_qty, 0)) AS net_qty, "
                        + "SUM(i.discount) AS total_discount FROM invoice i "
                        + "LEFT JOIN (SELECT invoice_id, SUM(qty) AS total_qty FROM invoice_item "
                        + "GROUP BY invoice_id) ii ON i.id = ii.invoice_id LEFT JOIN (SELECT invoice_id, "
                        + "SUM(return_total) AS return_total FROM customer_return_receipt "
                        + "GROUP BY invoice_id) crr ON i.id = crr.invoice_id "
                        + "LEFT JOIN (SELECT crr.invoice_id, SUM(cri.qty) AS return_qty FROM customer_return_item cri "
                        + "INNER JOIN customer_return_receipt crr ON cri.customer_return_receipt_id = crr.id "
                        + "GROUP BY crr.invoice_id) cri ON i.id = cri.invoice_id WHERE DATE(i.date) = CURDATE()");
                filePath = this.getClass().getResourceAsStream("/reports/gh_sales_daily.jasper");
            }else if (sort.equals("Weekly")) {
                date = new SimpleDateFormat("yyyy-MMMM-W").format(new Date());
                resultSet = MySQL.executeSearch("SELECT COUNT(i.id) AS invoice_count, "
                        + "SUM(i.paid_amount - IFNULL(crr.return_total, 0)) AS net_paid_amount, "
                        + "SUM(IFNULL(ii.total_qty, 0) - IFNULL(cri.return_qty, 0)) AS net_qty, "
                        + "SUM(i.discount) AS total_discount FROM invoice i "
                        + "LEFT JOIN (SELECT invoice_id, SUM(qty) AS total_qty FROM invoice_item "
                        + "GROUP BY invoice_id) ii ON i.id = ii.invoice_id LEFT JOIN (SELECT invoice_id, "
                        + "SUM(return_total) AS return_total FROM customer_return_receipt "
                        + "GROUP BY invoice_id) crr ON i.id = crr.invoice_id "
                        + "LEFT JOIN (SELECT crr.invoice_id, SUM(cri.qty) AS return_qty FROM customer_return_item cri "
                        + "INNER JOIN customer_return_receipt crr ON cri.customer_return_receipt_id = crr.id "
                        + "GROUP BY crr.invoice_id) cri ON i.id = cri.invoice_id WHERE WEEK(DATE(i.date)) = WEEK(CURDATE())");
                filePath = this.getClass().getResourceAsStream("/reports/gh_sales_weekly.jasper");
            }else if (sort.equals("Monthly")) {
                date = new SimpleDateFormat("yyyy-MMMM").format(new Date());
                resultSet = MySQL.executeSearch("SELECT COUNT(i.id) AS invoice_count, "
                        + "SUM(i.paid_amount - IFNULL(crr.return_total, 0)) AS net_paid_amount, "
                        + "SUM(IFNULL(ii.total_qty, 0) - IFNULL(cri.return_qty, 0)) AS net_qty, "
                        + "SUM(i.discount) AS total_discount FROM invoice i "
                        + "LEFT JOIN (SELECT invoice_id, SUM(qty) AS total_qty FROM invoice_item "
                        + "GROUP BY invoice_id) ii ON i.id = ii.invoice_id LEFT JOIN (SELECT invoice_id, "
                        + "SUM(return_total) AS return_total FROM customer_return_receipt "
                        + "GROUP BY invoice_id) crr ON i.id = crr.invoice_id "
                        + "LEFT JOIN (SELECT crr.invoice_id, SUM(cri.qty) AS return_qty FROM customer_return_item cri "
                        + "INNER JOIN customer_return_receipt crr ON cri.customer_return_receipt_id = crr.id "
                        + "GROUP BY crr.invoice_id) cri ON i.id = cri.invoice_id WHERE MONTH(DATE(i.date)) = MONTH(CURDATE())");
                filePath = this.getClass().getResourceAsStream("/reports/gh_sales_monthly.jasper");
            }
            
            if (resultSet.next()) {
                String totalSales = resultSet.getString("invoice_count");
                String totalRevenue = resultSet.getString("net_paid_amount");
                String totalUnitsSold = resultSet.getString("net_qty");
                String totalDiscounts = resultSet.getString("total_discount");

                InputStream path = filePath;
                HashMap<String, Object> parameters = new HashMap<>();
                parameters.put("Parameter1", date);
                parameters.put("Parameter2", totalSales);
                parameters.put("Parameter3", totalRevenue);
                parameters.put("Parameter4", totalUnitsSold);
                parameters.put("Parameter5", totalDiscounts);

                String appDir = new File("").getAbsolutePath(); // Get the application's directory
                String reportsFolder = appDir + File.separator + "ExportedReports"; // Main folder path
                // Create the main "ExportedReports" folder if it doesn't exist
                File mainDirectory = new File(reportsFolder);
                if (!mainDirectory.exists()) {
                    mainDirectory.mkdirs();
                }
                // Create subfolder for "Sales Reports" if it doesn't exist
                String salesReportsFolder = reportsFolder + File.separator + "Sales Reports";
                File salesDirectory = new File(salesReportsFolder);
                if (!salesDirectory.exists()) {
                    salesDirectory.mkdirs();
                }
                // Create subfolder for "Monthly Sales Reports" if it doesn't exist
                if (sort.equals("Daily")) {
                    salesReportsTypeFolder = salesReportsFolder + File.separator + "Daily Sales Reports";
                }else if (sort.equals("Weekly")) {
                    salesReportsTypeFolder = salesReportsFolder + File.separator + "Weekly Sales Reports";
                }else if (sort.equals("Monthly")) {
                    salesReportsTypeFolder = salesReportsFolder + File.separator + "Monthly Sales Reports";
                }
                String subSalesReportsFolder = salesReportsTypeFolder;
                File subSalesDirectory = new File(subSalesReportsFolder);
                if (!subSalesDirectory.exists()) {
                    subSalesDirectory.mkdirs();
                }
                // Path to export the PDF file (inside "Monthly Sales Reports" subfolder)
                if (sort.equals("Daily")) {
                    reportFilePath = subSalesReportsFolder + File.separator + "Daily_Sales_report_" + date + ".pdf";
                }else if (sort.equals("Weekly")) {
                    reportFilePath = subSalesReportsFolder + File.separator + "Weekly_Sales_report_" + date + ".pdf";
                }else if (sort.equals("Monthly")) {
                    reportFilePath = subSalesReportsFolder + File.separator + "Monthly_Sales_report_" + date + ".pdf";
                }
                String outputPath = reportFilePath;

                JasperPrint report = JasperFillManager.fillReport(path, parameters, MySQL.connection);
                JasperExportManager.exportReportToPdfFile(report, outputPath);
                logger.log(Level.INFO, "Exported " + sort + " sales report for " + date + " to: " + outputPath);
                JOptionPane.showMessageDialog(null, "PDF exported to: " + outputPath);
            }else {
                logger.log(Level.INFO, "Error exporting " + sort + " sales report for " + date);
                JOptionPane.showMessageDialog(this, "Error exporting report", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            //e.printStackTrace();
            logger.log(Level.WARNING, "Exception", e);
        }
    }//GEN-LAST:event_salesExportButtonActionPerformed

    private void otherViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherViewButtonActionPerformed
        ButtonModel type = buttonGroup1.getSelection();
        
        if (type == null) {
            JOptionPane.showMessageDialog(this, "Please select a type", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            try {
                String typeName = type.getActionCommand();
                InputStream filePath = null;
                
                if (typeName.equals("Employees")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_employees.jasper");
                }else if (typeName.equals("Customers")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_customers.jasper");
                }else if (typeName.equals("Suppliers")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_suppliers.jasper");
                }else if (typeName.equals("Products")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_products.jasper");
                }
                
                InputStream path = filePath;
                JasperPrint report = JasperFillManager.fillReport(path, null, MySQL.connection);
                JasperViewer.viewReport(report, false);
                logger.log(Level.INFO, "Viewed " + typeName + " report");
            } catch (Exception e) {
                //e.printStackTrace();
                logger.log(Level.WARNING, "Exception", e);
            }
        }
    }//GEN-LAST:event_otherViewButtonActionPerformed

    private void otherPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherPrintButtonActionPerformed
        ButtonModel type = buttonGroup1.getSelection();
        
        if (type == null) {
            JOptionPane.showMessageDialog(this, "Please select a type", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            try {
                String typeName = type.getActionCommand();
                InputStream filePath = null;
                
                if (typeName.equals("Employees")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_employees.jasper");
                }else if (typeName.equals("Customers")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_customers.jasper");
                }else if (typeName.equals("Suppliers")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_suppliers.jasper");
                }else if (typeName.equals("Products")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_products.jasper");
                }
                
                InputStream path = filePath;
                JasperPrint report = JasperFillManager.fillReport(path, null, MySQL.connection);
                JasperPrintManager.printReport(report, false);
                logger.log(Level.INFO, "Printed " + typeName + " report");
            } catch (Exception e) {
                //e.printStackTrace();
                logger.log(Level.WARNING, "Exception", e);
            }
        }
    }//GEN-LAST:event_otherPrintButtonActionPerformed

    private void otherExportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherExportButtonActionPerformed
        ButtonModel type = buttonGroup1.getSelection();
        
        if (type == null) {
            JOptionPane.showMessageDialog(this, "Please select a type", "Warning", JOptionPane.WARNING_MESSAGE);
        }else {
            try {
                String typeName = type.getActionCommand();
                String date = new SimpleDateFormat("yyyy-MMMM-dd").format(new Date());
                InputStream filePath = null;
                String otherReportsTypeFolder = "";
                String reportFilePath = "";
                
                if (typeName.equals("Employees")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_employees.jasper");
                }else if (typeName.equals("Customers")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_customers.jasper");
                }else if (typeName.equals("Suppliers")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_suppliers.jasper");
                }else if (typeName.equals("Products")) {
                    filePath = this.getClass().getResourceAsStream("/reports/gh_products.jasper");
                }
                
                InputStream path = filePath;
                String appDir = new File("").getAbsolutePath(); // Get the application's directory
                String reportsFolder = appDir + File.separator + "ExportedReports"; // Main folder path
                // Create the main "ExportedReports" folder if it doesn't exist
                File mainDirectory = new File(reportsFolder);
                if (!mainDirectory.exists()) {
                    mainDirectory.mkdirs();
                }
                // Create subfolder for "Other Reports" if it doesn't exist
                String otherReportsFolder = reportsFolder + File.separator + "Other Reports";
                File otherDirectory = new File(otherReportsFolder);
                if (!otherDirectory.exists()) {
                    otherDirectory.mkdirs();
                }
                // Create subfolder for "Product Reports" if it doesn't exist
                if (typeName.equals("Employees")) {
                    otherReportsTypeFolder = otherReportsFolder + File.separator + "Employee Reports";
                }else if (typeName.equals("Customers")) {
                    otherReportsTypeFolder = otherReportsFolder + File.separator + "Customer Reports";
                }else if (typeName.equals("Suppliers")) {
                    otherReportsTypeFolder = otherReportsFolder + File.separator + "Supplier Reports";
                }else if (typeName.equals("Products")) {
                    otherReportsTypeFolder = otherReportsFolder + File.separator + "Product Reports";
                }
                String subOtherReportsFolder = otherReportsTypeFolder;
                File subOtherReportsDirectory = new File(subOtherReportsFolder);
                if (!subOtherReportsDirectory.exists()) {
                    subOtherReportsDirectory.mkdirs();
                }
                // Path to export the PDF file (inside "Product Reports" subfolder)
                if (typeName.equals("Employees")) {
                    reportFilePath = subOtherReportsFolder + File.separator + "Employees_report_" + date + ".pdf";
                }else if (typeName.equals("Customers")) {
                    reportFilePath = subOtherReportsFolder + File.separator + "Customers_report_" + date + ".pdf";
                }else if (typeName.equals("Suppliers")) {
                    reportFilePath = subOtherReportsFolder + File.separator + "Suppliers_report_" + date + ".pdf";
                }else if (typeName.equals("Products")) {
                    reportFilePath = subOtherReportsFolder + File.separator + "Products_report_" + date + ".pdf";
                }
                String outputPath = reportFilePath;

                JasperPrint report = JasperFillManager.fillReport(path, null, MySQL.connection);
                JasperExportManager.exportReportToPdfFile(report, outputPath);
                logger.log(Level.INFO, "Exported " + typeName + " report to: " + outputPath);
                JOptionPane.showMessageDialog(null, "PDF exported to: " + outputPath);
            } catch (Exception e) {
                //e.printStackTrace();
                logger.log(Level.WARNING, "Exception", e);
            }
        }
    }//GEN-LAST:event_otherExportButtonActionPerformed

    private void closeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLabelMouseClicked
        this.home.removeReports();
    }//GEN-LAST:event_closeLabelMouseClicked

    private void reportTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_reportTypeComboBoxItemStateChanged
        loadReports();
    }//GEN-LAST:event_reportTypeComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel closeLabel;
    private javax.swing.JRadioButton customersRadioButton;
    private com.toedter.calendar.JDateChooser dateFromDateChooser;
    private com.toedter.calendar.JDateChooser dateToDateChooser;
    private javax.swing.JRadioButton employeesRadioButton;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton otherExportButton;
    private javax.swing.JButton otherPrintButton;
    private javax.swing.JButton otherViewButton;
    private javax.swing.JRadioButton productsRadioButton;
    private javax.swing.JComboBox<String> reportTypeComboBox;
    private javax.swing.JTable reportsTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton salesExportButton;
    private javax.swing.JButton salesPrintButton;
    private javax.swing.JComboBox<String> salesTypeComboBox;
    private javax.swing.JButton salesViewButton;
    private javax.swing.JComboBox<String> sortByComboBox;
    private javax.swing.JRadioButton suppliersRadioButton;
    // End of variables declaration//GEN-END:variables
}
