/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import static gui.SignIn.logger;
import model.MySQL;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author barth
 */
public class SelectReturnStock extends javax.swing.JDialog {
    private Returns supReturns;
    
    /**
     * Creates new form CompanyRegistration
     */
    public SelectReturnStock(java.awt.Frame parent, boolean modal, Returns supReturns) {
        super(parent, modal);
        this.supReturns = supReturns;
        initComponents();
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        returnStockTable.setDefaultRenderer(Object.class, renderer);
        loadStock();
    }
    
    private void loadStock() {
        try {
            String query = "SELECT * FROM `returning_stock` INNER JOIN `stock` "
                    + "ON `returning_stock`.`stock_id` = `stock`.`id` INNER JOIN `grn_item` "
                    + "ON `stock`.`id` = `grn_item`.`stock_id` INNER JOIN `grn` "
                    + "ON `grn_item`.`grn_id` = `grn`.`id` INNER JOIN `product` "
                    + "ON `stock`.`product_id` = `product`.`id` INNER JOIN `supplier` "
                    + "ON `grn`.`supplier_mobile` = `supplier`.`mobile` INNER JOIN `returning_stock_status` "
                    + "ON `returning_stock`.`returning_stock_status_id` = `returning_stock_status`.`id` "
                    + "WHERE `supplier`.`mobile` = '"+supReturns.suppliersMap.get(supReturns.getsupplierEmailLabel().getText())+"' "
                    + "AND `returning_stock_status`.`name` = 'Pending'";
            ResultSet resultSet = MySQL.executeSearch(query);
            DefaultTableModel model = (DefaultTableModel)returnStockTable.getModel();
            model.setRowCount(0);
            
            while (resultSet.next()) {
                Vector<String> vector = new Vector<>();
                vector.add(resultSet.getString("returning_stock.id"));
                vector.add(resultSet.getString("stock.barcode"));
                vector.add(resultSet.getString("product.name"));
                vector.add(resultSet.getString("returning_stock.qty"));
                vector.add(resultSet.getString("stock.mfd"));
                vector.add(resultSet.getString("stock.exp"));
                vector.add(resultSet.getString("grn_item.price"));
                model.addRow(vector);
            }
        } catch (Exception e) {
            //e.printStackTrace();
            logger.log(Level.WARNING, "Exception", e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        returnStockTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Return Stock");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("Select Return Stock");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        returnStockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "R. Stock ID", "Barcode", "Product Name", "Quantity", "MFD", "EXP", "Buying Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        returnStockTable.getTableHeader().setReorderingAllowed(false);
        returnStockTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnStockTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(returnStockTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnStockTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnStockTableMouseClicked
        int row = returnStockTable.getSelectedRow();
        
        if (evt.getClickCount() == 2) {
            if (supReturns != null) {
                try {
                    ResultSet resultSet = MySQL.executeSearch("SELECT * FROM `return_invoice_item` "
                            + "WHERE `returning_stock_id` = '"+String.valueOf(returnStockTable.getValueAt(row, 0))+"'");
                    
                    if (resultSet.next()) {
                        JOptionPane.showMessageDialog(this, "This return stock is already added", 
                                "Warning", JOptionPane.WARNING_MESSAGE);
                        this.dispose();
                    }else {
                        supReturns.getreturningStockIDLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 0)));
                        supReturns.getstockBarcodeField().setText(String.valueOf(returnStockTable.getValueAt(row, 1)));
                        supReturns.getproductNameLabel2().setText(String.valueOf(returnStockTable.getValueAt(row, 2)));
                        supReturns.getquantityLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 3)));
                        supReturns.getmfdLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 4)));
                        supReturns.getexpLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 5)));
                        supReturns.getbuyingPriceLabel().setText(String.valueOf(returnStockTable.getValueAt(row, 6)));
                        this.dispose();
                    }
                } catch (Exception e) {
                    //e.printStackTrace();
                    logger.log(Level.WARNING, "Exception", e);
                }
            }
        }
    }//GEN-LAST:event_returnStockTableMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable returnStockTable;
    // End of variables declaration//GEN-END:variables
}
